sudo: required
dist: trusty
matrix:
  include:
    - language: scala
      scala:
        - 2.12.4
    - language: python
      python:
        - 3.5
      install:
        - pip install nose coverage python-coveralls
      script:
        - nosetests -v --with-coverage --cover-package=. -w src/test/python/